include: package:lint/analysis_options.yaml

analyzer:
   errors:
      missing_return: error
      missing_required_param: error
      must_be_immutable: error
      parameter_assignments: error

linter:
   rules:
      public_member_api_docs: false
      lines_longer_than_80_chars: false
      prefer_relative_imports: true
      sort_unnamed_constructors_first: false

exclude:
   - "**/*.g.dart"
   - "**/*.freezed.dart"
   - "gen_dart/"
